version: "3.9"

# Ports
# 5100 - Application Port
# 5100 - Production Host port
# 5101 - Development Host port mapped to application port

# Container Names
# dev_ebook_library - Development Container 
# prod_ebook_library - Production Container

# Services Names
# dev_ebook_library - Development Service
# prod_ebook_library - Production Service


services:
  dev_ebook_library:
    build: .
    container_name: dev_ebook_library
    ports:
      - "5101:5100" # Map port 5100 inside the container to port 5101 on the host
    volumes:
      - ./:/app
      - ./ebooks:/app/ebooks # Folder containing your ebooks
      - ./metadata.db:/app/metadata.db # Persist your database
      - ./static:/app/static # Persist static files
      - ./templates:/app/templates # Persist templates
    restart: unless-stopped
