version: "3.9"

# Ports
# 5100 - Application Port
# 5100 - Production Host port
# 5101 - Development Host port mapped to application port


services:
  ebook-library:
    build: .
    container_name: ebook_library
    ports:
      - "5101:5100" # Map port 5100 inside the container to port 5101 on the host
    volumes:
      - ./:/app
      - ./ebooks:/app/ebooks # Folder containing your ebooks
      - ./metadata.db:/app/metadata.db # Persist your database
      - ./static:/app/static # Persist static files
      - ./templates:/app/templates # Persist templates
    restart: unless-stopped
